# Makefile for Xperiment68k (si)

TARGET = \
         si_acc.x si_emu.x si_memory.x si_midi.x si_model.x si_mpuclk.x \
         si_pcgexp.x si_phantomx.x si_scsiex.x si_sram.x

include ../common.mk

# EOF
