# Makefile for Xperiment68k (dos)

TARGET = \
         dos_chdir.x dos_chgdrv.x dos_chmod.x dos_conctrl.x dos_create_sp.x dos_curdir.x dos_curdrv.x \
         dos_exit2.x dos_fatchk.x dos_fgetc.x dos_fgets.x dos_filedate.x \
         dos_getc.x dos_getchar.x dos_getdate.x dos_getenv.x dos_gets.x dos_gettim2.x dos_gettime.x \
         dos_inkey.x dos_inpout.x dos_keyctrl01.x dos_maketmp.x dos_malloc2.x dos_mkdir.x \
         dos_nameck.x dos_namests.x dos_putchar.x dos_rmdir.x \
         dos_setdate.x dos_setenv.x dos_settim2.x dos_settime.x dos_vernum.x dos_wait.x

include ../common.mk

# EOF
