# Makefile for Xperiment68k (poc)

TARGET = \
         bglivingdead.x bgzombie.x bkeyinpd3.x chxdummy.x conctrl_so.x env_sbo.x fatchk_bof.x \
         incdir_test.x nameck_bof.x namests_bof.x ns_sbo.x pathchk_bof1.x pathchk_bof2.x \
         zerounit.sys

include ../common.mk

# EOF
