# Makefile for Xperiment68k (bg)

TARGET = \
         bg1pr2th.x bgchangeprc.x bgexec.x bgexecd.x bggetpr.x bgkill.x bgontime.x \
         bgsleeppr.x bgsprocd.x bgsprocess.x bgsuspendpr.x bgthreadid.x bgwakeup.x 

include ../common.mk

# EOF
