# Makefile for Xperiment68k (opmdrv)

O1 = m_alloc.x m_assign.x m_atoi.x m_cont.x m_free.x m_init.x \
     m_inton.x m_intoff.x m_play.x m_stat.x m_stop.x m_tempo.x m_trk.x

O2 = md_off.x md_on.x md_stat.x

O3 = m_freea.x m_ifchk.x m_use.x m_version.x

TARGET = $(O1) $(O2) $(O3) opmdrvtype.x

include ../common.mk

# EOF
