# Makefile for Xperiment68k (opmdrv)

TARGET = \
         m_alloc.x m_assign.x m_atoi.x m_cont.x m_free.x m_freea.x m_init.x m_inton.x m_intoff.x \
         m_play.x m_stat.x m_stop.x m_tempo.x m_trk.x m_use.x m_version.x \
         opmdrvtype.x

include ../common.mk

# EOF
