# Makefile for Xperiment68k (opmdrv)

O1 = m_alloc.x m_assign.x m_atoi.x m_cont.x m_free.x m_init.x \
     m_inton.x m_intoff.x m_play.x m_stat.x m_stop.x m_tempo.x m_trk.x

O2 = md_off.x md_on.x md_stat.x

O3 = m_antoff.x m_bend.x m_chan.x m_chget.x m_enable.x m_freea.x m_ifchk.x \
     m_mstvol.x m_mod.x m_modsns.x m_opmexc.x m_opmlfq.x m_opmreg.x \
     m_pan.x m_panflt.x \
     m_pcmbsy.x m_pcmget.x m_pcmlen.x m_pcmon.x m_pcmrec.x m_pcmset.x \
     m_pgmflt.x m_pnmget.x m_pnmset.x m_prog.x \
     m_sync.x m_sysch.x m_tnmget.x m_tnmset.x m_trkget.x m_trns.x m_use.x \
     m_vget.x m_vel.x m_version.x m_vol.x m_volflt.x m_vset.x m_ycom.x

TARGET = $(O1) $(O2) $(O3) opmdrvtype.x

include ../common.mk

# EOF
