# Makefile for Xperiment68k (file)

TARGET = \
         appendbytes.x closerewindatr.x exfiles.x existsdir.x fileop.x files.x getassign.x \
         ioctrl12.x ioctrl13.x newvol.x openedfiles.x pathlenfix.x rewind.x

include ../common.mk

# EOF
