# Makefile for Xperiment68k (iocs)

TARGET = \
         iocs_akconv.x iocs_b_clr_st.x iocs_b_conmod.x iocs_b_del.x iocs_b_drvchk.x iocs_b_ins.x \
         iocs_datebcd.x iocs_datebin.x iocs_dateget.x iocs_dateset.x \
         iocs_jissft.x iocs_ontime.x iocs_sftjis.x \
         iocs_timebcd.x iocs_timebin.x iocs_timeget.x iocs_timeset.x \
         iocs_txfill.x iocs_txyline.x iocs_txrascpy.x 

include ../common.mk

# EOF
