# Makefile for Xperiment68k (misc)

TARGET = \
         datetime.x dbrams.x exception.x hasophash.x joyget.x \
         midi_reg.x minish.x nminoreset.x \
         reset68k.r rtc_reg.x runwaitchk.x super_time.x sysport.x \
         tokikoe.x trap15trace.x vdispst_time.x

include ../common.mk

# EOF
